title: A new blog #1
author: cheif-99
email: oniabdulazeezbabalola@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test blog #1

# social links
twitter_username: babalol18128967 # DO NOT include the @ character, or else the build will fail!
github_username:  cheif-99 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
